### PR TITLE
fix log injection altering log entries unexpectedly in some cases

### LINKED ISSUE #931: Log Injection breaks Error objects
**Describe the bug**
When passing an `Error` object to `winston` (e.g. `log.error(new Error('oops'))`), the `log` plugin turns the `Error` into a plain `object` without the `message` and `stack` properties before passing it along to `winston`.

Here is a simple reproduction:
```
require('dd-trace').init({ logInjection: true })

const winston = require('winston')
const util = require('util')
const http = require('http')

const log = winston.createLogger({
  transports: [new winston.transports.Console()],
  format: winston.format.printf(util.inspect)
})

const app = require('express')()
app.get('/log', (req, res) => {
  log.error('good')
  log.error({ message: 'good' })
  log.error(new Error('not good'))
  res.send('')
})

app.listen(3003, () => {
  http.get('http://localhost:3003/log', () => {
    process.exit(0)
  })
})
```

Log output:
```
{
  dd: { trace_id: '1190699381420439375', span_id: '1245536781377984478' },
  message: 'good',
  level: 'error',
  [Symbol(level)]: 'error'
}
{
  dd: { trace_id: '1190699381420439375', span_id: '1245536781377984478' },
  message: 'good',
  level: 'error',
  [Symbol(level)]: 'error'
}
{
  dd: { trace_id: '1190699381420439375', span_id: '1245536781377984478' },
  level: 'error',
  [Symbol(level)]: 'error'
}
```

The third log entry is missing `message` because it is not iterable with `in`: https://github.com/DataDog/dd-trace-js/blob/d8d686736a5603c8925cef28b85879c3f37cd0ad/packages/dd-trace/src/plugins/util/log.js#L19

I feel like using `logInjection: true` should only augment log entries before passing them to `winston` and not modify them in a destructive way like this.

**Environment**

* **Operation system: OS X**
* **Node version: 12.14.0**
* **Tracer version: ?**
* **Agent version: ?**

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix log injection altering log entries unexpectedly in some cases.

### Motivation

The current implementation creates a new object and copies all properties of the actual record. This doesn't work in every case as some properties may be missed, especially with complex objects like error instances.

Instead, we now rely on the library to do the copy for us when possible, and otherwise inject only for the duration of the log function after which the additional property is removed to make sure we are not impacting the rest of the app which may rely on the structure of the record.

Fixes #931

### CODE REVIEW

**Comment by jbarrus** [comment]
@bengl This fixed the logging of error objects for me, but I now no longer get trace and span injection happening. I didn't dig too far into it, but I put some console log statements in the code:

```
function createWrapPino (tracer, config) {
  console.log('createWrapPino');
  return function wrapPino (pino) {
    console.log('wrapPino');
    return function pinoWithTrace () {
      console.log('pinoWithTrace');
      const instance = pino.apply(this, arguments)
      const asJsonSym = (pino.symbols && pino.symbols.asJsonSym) || 'asJson'

      Object.defineProperty(instance, asJsonSym, {
        configurable: true,
        enumerable: true,
        writable: true,
        value: createWrapAsJson(tracer, config)(instance[asJsonSym])
      })

      return instance
    }
  }
}

function createWrapAsJson (tracer, config) {
  console.log('createWrapAsJson');
  return function wrapAsJson (asJson) {
    console.log('wrapAsJson');
    return function asJsonWithTrace (obj, msg, num, time) {
      console.log('asJsonWithTrace');
      const span = tracer.scope().active()

      obj = arguments[0] = obj || {}

      console.log('inject');
      tracer.inject(span, LOG, obj)
      console.log('after inject');

      const json = asJson.apply(this, arguments)

      obj && delete obj.dd

      return json
    }
  }
}
```

and all the output I get is

```
createWrapPino
wrapPino
```

Never seems to hit the "createWrapAsJson"  function.

**Comment by rochdev** [comment]
@jbarrus Which version of `dd-trace` and of `pino` are you using?

**Comment by rochdev** [comment]
@jbarrus Also, do you see any error logs from plugin initialization when you use `DD_TRACE_DEBUG=true`? (quite verbose so use only for a short period of time)

One common reason too why plugins are not working properly is if the tracer was initialized after the instrumented module was imported. Can you share how and where you initialize the tracer?

**Comment by jbarrus** [comment]
```
{
 "pino": "^6.3.2",
}

**Comment by rochdev** [comment]
Ok, this version is definitely supported and we have test coverage for it, so I would suspect the initialization order as described above.

**Pull request merged**
