### PR TITLE
Update trivially upgraded dependencies

### PR DESCRIPTION
**Pull request by Qard**
### What does this PR do?

Updates all dependencies which can be updated without needing code changes to maintain current test status on all active release lines. I've tested this locally on Node.js 12 and everything passes.

### Motivation

Trying to figure out the best dependency upgrade strategy to avoid npm/yarn audit errors reporting and/or getting scared off by vulns that aren't really there.

### CODE REVIEW

**Review by simon-id — APPROVED** [review]

**Comment by Qard** [comment]
@astuyve I seem to be getting consistent failures from the serverless integration test on this now for some reason. Has anything changed there recently? Did I bump any dependencies in here that you're depending on?

**Comment by astuyve** [comment]
Hey, this looks like a setup function for GCP - the function wasn't deployed correctly and doesn't exist. I'll get someone to look into it, but it's probably safe to ignore.

Does this fail on main?

**Comment by Qard** [comment]
Doesn't appear to fail on main, no. Just in this PR, so I suspect one of the dependencies I've updated broke something, but I'm not sure what. 🤔

**Comment by astuyve** [comment]
Looks like this is fixed here: https://github.com/DataDog/dd-trace-js/pull/3418

**Comment by Qard** [comment]
@astuyve Seems to just be failing for a different reason now?

**Comment by rochdev** [comment]
@Qard Another fix just landed, hopefully it should no longer be flaky.

**Pull request merged**
