### PR TITLE
`v1.7.0` 

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
`1.7.0` release branch. 

Cherry picked commits: 
* From https://github.com/DataDog/dd-trace-js/pull/1718: https://github.com/DataDog/dd-trace-js/commit/854783f7c7b70ffd136d71c85d0bb07f2c7c4323
* From https://github.com/DataDog/dd-trace-js/pull/1706: https://github.com/DataDog/dd-trace-js/commit/21179be27f7f9487e8287056fa08e404f5e6ef14
* From https://github.com/DataDog/dd-trace-js/pull/1744: https://github.com/DataDog/dd-trace-js/commit/bf46fd17e128c3082c805bc8412005453b5ba76d
* From https://github.com/DataDog/dd-trace-js/pull/1725: https://github.com/DataDog/dd-trace-js/commit/abf0fda1c243e0eda63337cf93989e96ab687f91
* From https://github.com/DataDog/dd-trace-js/pull/1745: https://github.com/DataDog/dd-trace-js/commit/8089dd1e368df2c4ebc54e6d23e48d3d7ff0479a
* From https://github.com/DataDog/dd-trace-js/pull/1746: https://github.com/DataDog/dd-trace-js/commit/37e12b63fa8e2d3aaf76302e3cc037eee45cff55
* From https://github.com/DataDog/dd-trace-js/pull/1734: https://github.com/DataDog/dd-trace-js/commit/83bedeb761bb8697dd3a7358975593bae12c3663
* From https://github.com/DataDog/dd-trace-js/pull/1730: https://github.com/DataDog/dd-trace-js/commit/9e3a379a9d95b32063c540d9fd78a8ef78ab923e
* From https://github.com/DataDog/dd-trace-js/pull/1749: https://github.com/DataDog/dd-trace-js/commit/3ac50b0b94a520197ab5ff39898024c203b391b0
* From https://github.com/DataDog/dd-trace-js/pull/1753: https://github.com/DataDog/dd-trace-js/commit/af0e1dceffca785d343957f5dc4f618fb9d1e2c4
* From https://github.com/DataDog/dd-trace-js/pull/1762: https://github.com/DataDog/dd-trace-js/commit/0ec843c5a692405a0d90750892daafbc2964e8dd
* From https://github.com/DataDog/dd-trace-js/pull/1757: https://github.com/DataDog/dd-trace-js/commit/9f189f525929ec7309b3ca21014ecb19df151f2b
* From https://github.com/DataDog/dd-trace-js/pull/1759: https://github.com/DataDog/dd-trace-js/commit/d9e367d93ef037d370e26b3c456896ad8f12ddb0
* From https://github.com/DataDog/dd-trace-js/pull/1764: https://github.com/DataDog/dd-trace-js/commit/0b63cfe04e32b73c5d5836aac8cd6fae4304b8e9
* From https://github.com/DataDog/dd-trace-js/pull/1766: https://github.com/DataDog/dd-trace-js/commit/9abb0e3528ea793131bd91fb63f4b760d9f2d92f

Skipped commits:
* From https://github.com/DataDog/dd-trace-js/pull/1741: https://github.com/DataDog/dd-trace-js/commit/8c40e6f3340b7e9d75db90194e84986e36e82d70 
* From https://github.com/DataDog/dd-trace-js/pull/1751: https://github.com/DataDog/dd-trace-js/commit/72a2d7aa4d9e5e6a0d8771feb23bb00b15d7f33a
* From https://github.com/DataDog/dd-trace-js/pull/1743: https://github.com/DataDog/dd-trace-js/commit/cf9bc9c7cb8e9fa8282fbde591826888b32ea3e5

### CODE REVIEW

**Comment by rochdev** [comment]
> Skipped commits (are we releasing changes to the plugin system?)

@bengl These are all fine to release right?

**Comment by bengl** [comment]
@rochdev yeah LGTM

**Review by bengl — APPROVED** [review]

**Review by rochdev — DISMISSED** [review]

**Comment by juan-fernandez** [comment]
just pushed the skipped commits as they're safe

**Comment by juan-fernandez** [comment]
reverting the skipped commits, as they seem to depend on https://github.com/DataDog/dd-trace-js/pull/1645, which we don't want to release yet

**Review by rochdev — APPROVED** [review]

**Pull request merged**
