### PR TITLE
Added histogram method to dogstatsd

### PR DESCRIPTION
**Pull request by bin-umar**
### What does this PR do?
It adds missing .histogram method to datadogstatsd, which exist in other cdk-s: python, ruby, go, rust, etc. https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/#histogram

### Motivation
To be able to use the same code in js cdk as in other platforms. Right now I need this implementation in our api.

### Plugin Checklist

- [x] Unit tests.
- [x] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### Security 
Datadog employees:
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by bin-umar** [comment]
@uurien @iunanua @rochdev could u please help to unblock this PR?

**Comment by bin-umar** [comment]
@bengl hi, can u please do something? :)

**Comment by bin-umar** [comment]
@Qard @jbertran @szegedi @nsavoire anyone, could u please help guys?

**Comment by ida613** [comment]
Thank you for your contribution! could you fix the failing tests? I can look into how to fix them after finishing my work at hand

**Comment by bin-umar** [comment]
> Thank you for your contribution! could you fix the failing tests? I can look into how to fix them after finishing my work at hand

Thanks for response! Yes, of course, just CI was blocked because of missing labels. I'll do asap.

**Comment by bin-umar** [comment]
@ida613 I've looked to failed actions, looks like most of them are network issues:
- [CI Visibility performance and correctness tests](https://github.com/DataDog/dd-trace-js/actions/runs/8374076907/job/23164559070#logs) -> GitHub API response code: 401
- [build-and-publish-init-image](https://github.com/DataDog/dd-trace-js/actions/runs/8374076920/job/23164559374) -> : unexpected status from POST request to https://ghcr.io/v2/datadog/dd-trace-js/dd-lib-js-init/blobs/uploads/: 403 Forbidden
- [Compute module size tree and report](https://github.com/DataDog/dd-trace-js/actions/runs/8374076908/job/23164559243) -> Error: Resource not accessible by integration
- yarn test:trace:core:ci -> there was test problem, fixed.
- [system-tests](https://github.com/DataDog/dd-trace-js/actions/runs/8374076914/job/23167446385#logs) -> container 1e1efa1ab172054a645347554a90a4ee939b5cb6e1946595aeb91685685d8305 is not running
- [test:plugins:ci](https://github.com/DataDog/dd-trace-js/actions/runs/8374076916/job/23164574454) -> error Error: https://registry.yarnpkg.com/safe-buffer/-/safe-buffer-5.1.2.tgz: Request failed "500 Internal Server Error"

**Comment by bin-umar** [comment]
@ida613 can we speed up please?

**Comment by bin-umar** [comment]
@juan-fernandez @bengl @tlhunter @nathanmarks @alloy @felixge anyone please :(((

**Comment by juan-fernandez** [comment]
> @juan-fernandez @bengl @tlhunter @nathanmarks @alloy @felixge anyone please :(((

hey @bin-umar , sorry for the delays. I've pushed your branch to https://github.com/DataDog/dd-trace-js/pull/4219 to run all the priviledged jobs

**Review by juan-fernandez — APPROVED** [review]

**Comment by bin-umar** [comment]
@juan-fernandez could you please direct us with nearest release?

**Comment by juan-fernandez** [comment]
hey @bin-umar you can always see the most recent release in https://github.com/DataDog/dd-trace-js/releases. As for the next one, it will be next week, unclear exactly when 😄

**Comment by bin-umar** [comment]
> hey @bin-umar you can always see the most recent release in https://github.com/DataDog/dd-trace-js/releases. As for the next one, it will be next week, unclear exactly when 😄

I'm looking for it actively :) just needed it for planning

**Comment by bin-umar** [comment]
@juan-fernandez Hi! Is it really big problem to publish new release? We're waiting this small change for a month. I can't see any problems to make simple `npm publish` with patch version.

**Comment by juan-fernandez** [comment]
new releases include these changes 😄 :

* [v3.56.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.56.0)
* [v4.35.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.35.0)
* [v5.11.0](https://github.com/DataDog/dd-trace-js/releases/tag/v5.11.0)

**Pull request merged**
