### PR TITLE
Update pprof-nodejs to 2.0.0

### PR DESCRIPTION
**Pull request by nsavoire**
### What does this PR do?
Update to new major version of prpof-nodejs
pprof-nodejs 2.0.0 uses pprof-format instead of protobufjs to encode profiles, that is why exporter test needs to be updated.

### Motivation
pprof-nodejs 2.0.0 contains fixes/improvements compared to previous version.

### CODE REVIEW

**Review by tlhunter — APPROVED** [review]
test

**Review by tlhunter — APPROVED** [review]

**Comment by tlhunter** [comment]
The two test failures are unrelated.

The performance gains are great!

**Comment by ddyurchenko** [comment]
Hi @nsavoire, it is nice to meet you!

Do you have some suggestions how we can make profiler benchmarks more meaningful?

**Comment by nsavoire** [comment]
> Hi @nsavoire, it is nice to meet you!
> 
> Do you have some suggestions how we can make profiler benchmarks more meaningful?

Hi @ddyurchenko, nice to meet you too !
Currently profiler benchmarks just start the requested profiler with a 0 second upload period and wait for the upload period to complete. In the end what we are measuring is profiler start up time plus time to encode/serialize an almost empty profile.

**Pull request merged**
