### PR TITLE
Re-implement the logger with diagnostics channel

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Re-implement the logger with diagnostics channel.

### Motivation

This will enable us to send logs as events to diagnostics channels instead of calling the logger directly. This has several benefits for our use case:

* Diagnostics channel has built-in support for checking for subscribers in order to avoid running whatever code is needed to build the log message. This is more efficient than the current callback approach. I haven't changed the usage in this PR as it can be done later in separate PR.
* We can do other things with the events, for example collect telemetry for the number of errors, etc.
* It could potentially allow using multiple loggers more easily, especially ones with different log levels.
* Allow us to eventually publish asynchronously to fix using log injection on a logger that is also set on the tracer.

### CODE REVIEW

**Comment by simon-id** [comment]
wild idea: what about doing this instead
```js
startupFailureLogChannel.subscribe((data) => {
  console.log(`The tracer could not start: ${data.error}`)
})

startupFailureLogChannel.publish({ error })
```

instead of having log level channels, we'd have specific log message/event channels.
any thoughts ?

**Comment by rochdev** [comment]
> instead of having log level channels, we'd have specific log message/event channels.

@simon-id That could potentially mean a lot of channels. An alternative to this would be to keep less channels and add some error type or error code or something like that. Originally that's how it was implemented but it was unclear if this would be useful, and made it more complicated to emit logs. Generally speaking, I think sending logs to just a few streams is enough. A good example of this is `stdout` and `stderr`.

In any case, I'm not against the idea, but if we're gonna go in that direction we should definitely define these really well to avoid having to add channels to core every time we add logging. Did you have a use case in mind where it would be helpful to have more granular log channels?

@bengl Thoughts?

**Comment by simon-id** [comment]
> Did you have a use case in mind where it would be helpful to have more granular log channels?
Nothing specific in mind, just a thought.

**Comment by Qard** [comment]
It's probably a good idea to at least split up by feature. For example, a user could decide to listen to only profiler messages. What I think would _actually_ be best is to create a module similar to https://www.npmjs.com/package/debug that would export a function which receives a namespace fragment and uses that with some datadog-specific prefix to create a diagnostics_channel and register it with a centralized logger. Whenever a new namespace is given, the created channel would be stored in a list that could separately be subscribed to any time logging is enabled globally.

This way users could use diagnostics_channel directly for logging and listen for very specific events. It'd be super helpful for debug logging too if we could tell a user specific sets of channels to listen to. Currently turning on certain levels of logging can be _very_ noisy. 😅 

We could also have a similar comma-separated env var to turn logging of specific channels on.

**Comment by rochdev** [comment]
@Qard What API would you propose? I agree that it would make sense to be able to turn on or off more granular logging, but I have a few concerns with this right now:

- The matrix might become complicated since users could want for example all profiling logs, or all debug logs regardless of the component, or all exporter logs regardless of level or component. I think this is less trivial than it seems at a glance.
- Being too granular could confuse users that don't know dd-trace extremely well. Standard log levels are universally understood, and while verbose, they are easy to use.
- Right now dd-trace internals are very coupled with little separation of concerns. This makes it difficult to clearly identify the namespace that a log record should belong to.

An alternative would also be to publish objects instead of strings and keep the current channels. Then you could for example subscribe to the `debug` channel and filter in your subscriber what is interesting to you. This would have the disadvantage of being more costly since it would generate the messages even if not needed (at least on the subscribed to channel), but it might be simpler to interact with, more flexible, and wouldn't require constantly adding new channels to core.

**Comment by Qard** [comment]
RegExp matching support was rejected in core when I originally built diagnostics_channel due to it being a lot more costly than string matching. It'd happen only at channel creation time so to _me_ it's not a big deal but just be warned it could get rejected again.

Also, I would not worry about exploding quantity of channels. It's _supposed_ to have many channels, it gains its performance advantage over a plain event emitter by reducing individual event types to separate channel objects which manage their own subscriber set independently. This is what enables zero-cost publishes when there are not listeners.

I do agree that we should figure out a standard for channel names though. Something like `$module:$subsystem:$purpose` makes sense to me.

**Comment by tlhunter** [comment]
Closing this one out as it's pretty old and has a lot of conflicts.

**Pull request closed without merging**
