### PR TITLE
fix requests to the agent being traced

### LINKED ISSUE #1248: dd-trace reports its own activity as APM http traces
**Describe the bug**
Datadog is receiving extremely frequent traces like the attached screenshot, which are tracing the activity of dd-trace itself sending traces to the agent on localhost.

image

A workaround is manually adding the URL to the http blocklist solves the issue, like this
```
import tracer from 'dd-trace'
tracer.init()
tracer.use('http', {
  blocklist: ['http://localhost:8126/v0.4/traces']
})
export default tracer
```

**Environment**

Running in ECS Fargate with agent as a sidecar container.

"datadog/agent:latest"

Agent container definition (in Terraform HCL representation, not JSON)
```
  datadog_agent_container_definition = {
    name      = "datadog-agent"
    image     = "datadog/agent:latest"
    essential = true
    environment = [
      {
        name  = "DD_APM_ENABLED"
        value = "true"
      },
      {
        name  = "ECS_FARGATE"
        value = "true"
      }
    ]
    secrets = [
      {
        name      = "DD_API_KEY",
        valueFrom = data.aws_secretsmanager_secret.datadog_api_key.arn
      }
    ]
    # Expose port 8126 so that the dd-trace instrumentation in our app can deliver traces to
    # the Datadog agent
    portMappings = [
      {
        hostPort      = 8126
        protocol      = "tcp"
        containerPort = 8126
      },
    ]
    # Apply tight limits on how much CPU/memory can be used by the agent container.
    cpu    = 10
    memory = 256
    # Define these empty values to avoid unnecessary diffs (default is [], Terraform tries to set 'null')
    mountPoints = []
    volumesFrom = []
  }
```

App container definition:
```
base_container_definition = {
    name  = local.app_container_name
    image = var.image
    essential = true
    environment = [

      {
        name  = "DD_TRACE_AGENT_HOSTNAME"
        value = "localhost"
      },
      {
        name  = "DD_SERVICE"
        value = var.name
      }
    ]
    logConfiguration = {
      logDriver = "awsfirelens"
      options = {
        Name           = "datadog"
        apikey         = local.datadog_api_key
        Host           = "http-intake.logs.datadoghq.com"
        dd_service     = var.name
        dd_source      = "firelens"
        dd_message_key = "log"
        TLS            = "on",
        provider       = "ecs"
      }
    }
    # Define these empty values to avoid unnecessary diffs (default is [], Terraform tries to set 'null')
    cpu          = 0
    mountPoints  = []
    volumesFrom  = []
    portMappings = []
  }
```

* **Node version:**
14
* **Tracer version:**
```
$ yarn list dd-trace
yarn list v1.22.10
└─ dd-trace@0.31.0
```
* **Agent version:**
`:latest` tag

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix requests to the agent being traced.

### Motivation

Fix #1248 which was introduced in #1108

### CODE REVIEW

**Comment by bengl** [comment]
Can you add a regression test?

**Comment by rochdev** [comment]
> Can you add a regression test?

There is already one.

**Comment by bengl** [comment]
>> Can you add a regression test?

> There is already one.

Which one?

**Comment by rochdev** [comment]
This did not previously use an actual no-op so it wasn't failing as it should have: https://github.com/DataDog/dd-trace-js/pull/1274/files#diff-b01d8cfed2fb6fc486db2e547b80f1a3304e6643d41ed8f572497384e863de4cR301

**Review by bengl — APPROVED** [review]

**Pull request merged**
