### PR TITLE
Use unified Gitlab pipeline for APM libraries

### PR DESCRIPTION
**Pull request by randomanderson**
### What does this PR do?

* Converts the Gitlab workflow to use the unified pipeline.
* Removes github actions and other scripts for things that are taken over by the pipeline

### Motivation
By using the unified pipeline across all APM libraries, there is less maintenance hassle, fewer mistakes, and a more uniform creation of artifacts.

### Additional Notes
"Gitlab Stages" as a concept just doesn't work anymore. Everything needs explicit dependencies and job execution order is wholly specified by those dependencies. That is why there are changes to the benchmark jobs to add `needs`

### CODE REVIEW

**Review by Qard — COMMENTED** [review]
Previously the `release-*.yml` files were giving us separate builds for each release line, but it seems like that goes away with this change? Do we lose the ability to build for multiple release lines at once? Also, is this running on every branch? Just master? I think to support our release lines it'd need to run on each of our release line branches. 🤔

**Comment by randomanderson** [comment]
@Qard These pipeline runs on every push. For k8s injection, the image is tagged with the commit sha. For OCI images, the version is the version from the repo + the pipeline id + the commit sha.

For releases, the git tag is used as the init image tag and the OCI image version.

I don't believe any of your current processes will be disrupted

**Comment by Qard** [comment]
Ah, so triggering off github releases is how we get the official release builds? Is it _desirable_ for this to be running on all pushes everywhere? That seems like a lot of unnecessary work. 🤔 

In any case, as long as this doesn't disrupt our existing customer expectations from this, I think we're good. 🙂

**Comment by randomanderson** [comment]
> Ah, so triggering off github releases is how we get the official release builds? Is it desirable for this to be running on all pushes everywhere? That seems like a lot of unnecessary work. 🤔

@Qard Yes. We have automated tests that run as part of CI/CD. These builds are running on the Gitlab infra so cost is negligible

**Review by bengl — APPROVED** [review]

**Pull request merged**
