### PR TITLE
fix broken plugin links

### PR DESCRIPTION
**Pull request by khanayan123**
### What does this PR do?
fixes broken plugin links on api.md doc

### Motivation
broken api docs

### CODE REVIEW

**Review by rochdev — CHANGES_REQUESTED** [review]
Wouldn't this make any existing links continue to break?

**Comment by khanayan123** [comment]
> Wouldn't this make any existing links continue to break?

existing links are already broken:

current broken link:

https://datadoghq.dev/dd-trace-js/interfaces/plugins.amqp10.html

proposed change:

https://datadoghq.dev/dd-trace-js/interfaces/export_.plugins.amqp10.html

**Comment by tlhunter** [comment]
> Wouldn't this make any existing links continue to break?

Are you referring to links on third party sites like github issues?

**Review by rochdev — APPROVED** [review]

**Review by tlhunter — APPROVED** [review]

**Comment by mjperrone** [comment]
It appears that the links are still broken on `master`. I just clicked the `express` link [here](https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md), which lead me to a 404 [here](https://github.com/DataDog/dd-trace-js/blob/master/docs/interfaces/export_.plugins.express.html).

**Pull request merged**
