### PR TITLE
[core] Next.js: Don't Trace Middleware

### LINKED ISSUE #3682: [Next.js] TypeError: Cannot read properties of undefined (reading 'url')
Received following error when loading page from app folder.
`
TypeError: Cannot read properties of undefined (reading 'url')
    at NextPlugin.pageLoad (webpack://hello/./node_modules/dd-trace/packages/datadog-plugin-next/src/index.js?:89:27)
    at eval (webpack://hello/./node_modules/dd-trace/packages/datadog-plugin-next/src/index.js?:17:55)
    at Subscription._handler (webpack://hello/./node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js?:14:9)
    at Channel.publish (node:diagnostics_channel:54:9)
    at NextNodeServer.findPageComponents (webpack://hello/./node_modules/dd-trace/packages/datadog-instrumentations/src/next.js?:86:23)
    at NextNodeServer.renderPageComponent (/Users/jack/hello/node_modules/next/dist/server/base-server.js:1579:35)
    at NextNodeServer.renderPageComponent (/Users/jack/hello/node_modules/next/dist/server/next-server.js:410:22)
`

**Environment**

* **Operation system:** mac ventura
* **Node.js version:** 16.11.1
* **Tracer version:** 4.16.0
* **Agent version:** : Compile time error
* **Relevant library versions:** Next Js version: 13.5.1

### PR DESCRIPTION
**Pull request by sabrenner**
### What does this PR do?
Removes middleware tracing. 

### Motivation
~~Removing `render` function tracing is a response to a long-standing `TODO` - they aren't needed currently, and don't add anything meaningful to the tracing process (taking them out doesn't change tests success rate or appearance of traces in the UI).~~

~~Tracing `render` functions is still important, as some are provided on the top-level API (ie `app.render(...)`) and should be supported in tracing. However, some of what we were tracing before was not part of this top-level API - this PR reflects this properly now (`render`, `renderToHTML`, `renderError`, `renderErrorToHTML`, `render404`).~~

Removing `middleware` tracing fixes #3682. Newer versions of Next.js route requests coming in to the middleware through the same handler function we currently trace, making us start a span for middleware. Then, requests get re-routed from the middleware by throwing an error caught higher up than where we trace. So, not only do we finish the trace with an error, but when we go to trace the actual request endpoint with the same request object, we don't end up tracing it, as we check if we have already. Yet, the `pageLoad` logic still runs on our side, but not in the context of a span, so our logic breaks. By not tracing middleware at all, we still trace the actual request itself, and the problem is avoided. This is tested by just adding a middleware function, and ensuring that existing tests don't break (before, adding a middleware file without changes to instrumentation would break ~50% of tests).

It's unclear if middleware was ever traced properly in the first place, so not tracing it altogether until we find a better way to do it shouldn't remove useful spans.

### CODE REVIEW

**Comment by Qard** [comment]
Wouldn't this mean those span types go away therefore making this semver-major?

**Comment by sabrenner** [comment]
@Qard that's a good point. Let me put this back into draft and take a look at it - from my own experience, I've only ever seen a _final_ `next.request` span without ones underneath it (ie what I would have expected to be another `next.request` span for the render functions), which to me suggests that the methods we traced weren't doing anything. So, I'm not sure what the impact is. We can take this discussion offline possibly, but let me take a look into it myself first and assess it.

**Comment by sabrenner** [comment]
@Qard I have a better understanding now - I wasn't aware how these functions could be used from the top-level API that Next.js provides (overriding parts of the request/response objects, and not just going through the default Next.js request handler). In that case, I'd say it's better (in reference to the removed `TODO` comment) to make sure _all_ of them are instrumented (from the top level Next.js API). Let me know what you're thoughts on this are, but I'll put this PR back into draft while I work on that.

**Comment by sabrenner** [comment]
@Qard I changed this a bit to trace `render` methods that can be used in custom servers. The ones removed (`renderToResponse` and `renderErrorToResponse`) are called from methods traced in this PR (`render` and `renderToHTML`), so this aspect shouldn't remove span types.

However, I'm interested in hearing if "removing" middleware tracing (for now) would still be considered a major change, since it's unclear if it worked properly in the first place (in recent versions of Next.js, definitely not, and in older versions, it didn't have a page resource attached, and wasn't properly labeled as a "middleware" span anyways). Since this issue is blocking some users, it would be nice to get this change out sooner.

**Comment by rochdev** [comment]
> The ones removed (renderToResponse and renderErrorToResponse) are called from methods traced in this PR (render and renderToHTML), so this aspect shouldn't remove span types.

These methods are public and could be called by user code directly as well (or by other parts of the framework internally).

**Comment by sabrenner** [comment]
@rochdev yeah that makes sense, and that's what I came to understand. I think I was thinking that it would be more clear that we're properly tracing top-level/public API render methods by doing it the way I did in my last commit. However, I do see your point, and I guess the idea in the past, of just wrapping the common methods that lie within the code path (in this case, `renderToResponse` and `renderErrorToResponse`) makes more sense. Bit of a big loop around that doesn't result in any change, but I'll change it back to how it was before this PR 😛 

However, I'm interested in your thoughts on the middleware bit as well - is skipping it (for now) considered a major change if it never worked properly in the first place? Again, I don't want to block this PR on a major release since this issue is blocking users, so any additional input on this is appreciated!

**Comment by Qard** [comment]
Can you describe specifically what the behaviour was that it did not work and how it differs with this change? It could be reasonable to treat as a bug fix if it was _completely_ broken, but we might want to be more careful with it if it was only subtly or conditionally broken. 🤔

**Comment by sabrenner** [comment]
For sure, this is something that's conditional on the version of Next.js, and something I've been exploring to verify the behavior of and interaction with our tracer.

---

_**TL;DR**_ based on some workarounds I've been trying, the problem described in this PR and in the original GH issue can be solved, and is something I'm currently working on testing. There are some other abnormalities with the structure of traces when using middleware that I'm investigating as well, and in general there are some implementation details we can discuss offline as to not pollute this PR. Hopefully, this will result in the direction of this PR to be moved to better supporting middleware in our Next.js integration.

---

For versions before 13.4 (which is also around when they started using workers internally for performance benefits), middleware calls happen inside the same `handleRequest` (the top-level request function that we trace from Next.js API), meaning that we just get a single `next.request` span - this is totally fine.

In versions above 13.4, it looks like this behavior changed, where now the `handleRequest` is called twice sequentially, once for the middleware, then reused again for the actual request endpoint. For versions before 13.5.x, this works fine (in that it doesn't crash, although the trace structure looks exceptionally off, which is something I'm trying to address). The middleware trace shows up as an additional `next.request` span.

In newer versions (>=13.5), Next.js re-directs middleware requests through its routes handler/resolver by throwing an error. This broke us initially because of how we finish spans when an error occurs, and it was being caught higher than where we trace. Additionally, the request now cannot be traced in the second invocation of the request handler, as we check not to trace the same request twice, meaning when we try to get a request object for a span that doesn't exist, we crash. However, I have a fix for this that I am currently testing, and shouldn't have to skip middleware at all.

We can continue some implementation-specific conversations more offline, but that's the gist of it.

In general, I think this PR can move more towards supporting middleware more fully, first through the mentioned bug fix, and then ironing out how it appears in traces.

**Review by Qard — APPROVED** [review]

**Review by tlhunter — APPROVED** [review]

**Comment by jackjennings** [comment]
@sabrenner I'm eagerly awaiting this functionality; is there any estimate of when the next minor version release might go out?

**Comment by kimzeevaarders** [comment]
This problem seems to have reoccured in our DD environment after we upgraded nextjs to v14.2.14 (dd-trace running on  v5.20.0) 🤔

**Comment by jeremy-ap** [comment]
seeing this error too - nextjs `14.2.15` and dd-trace `5.12.0`

**Comment by tlhunter** [comment]
@kimzeevaarders @jeremy-ap can you upgrade to the latest version of dd-trace and confirm if the issue is still happening? Namely `v4.51.0` / `v5.27.0`. There was a major bug with Next.js v14.2.7+ that was fixed in the most recent version and I'd like to rule that out as a cause.

**Comment by kimzeevaarders** [comment]
Hi, cool, yes I believe we already have a release with the newest version prepared. I'll let you know asap!

**Pull request merged**
