### PR TITLE
[ci-visibility] Remove `jest-jasmine2` code

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
Remove `jest-jasmine2` instrumentation code, since it was only used in 3.x release line and it's already EOL. 

### Motivation
Now that v3 is EOL, we no longer need to keep this code around.

### CODE REVIEW

**Review by anmarchenko — APPROVED** [review]

**Comment by simon-id** [comment]
Isn't this a breaking change that should land in v6 ? :thinking:

**Comment by juan-fernandez** [comment]
> Isn't this a breaking change that should land in v6 ? 🤔

nope, this was a breaking change in v4. We just had to carry the code around until v3 was EOL 😄: https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md#30-to-40

**Comment by juan-fernandez** [comment]
> > Isn't this a breaking change that should land in v6 ? 🤔
> 
> nope, this was a breaking change in v4. We just had to carry the code around until v3 was EOL 😄: https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md#30-to-40

notice that the code was checking `DD_MAJOR < 4`: https://github.com/DataDog/dd-trace-js/pull/4315/files#diff-74a96f6d5ac2137dcdae2e86565193c9f9a46b10276918a309dd19f974da1353L871

**Comment by juan-fernandez** [comment]
to clarify: this is strictly no-op for anything <v4, which we no longer make updates for, hence why I marked it as `semver-patch`

**Comment by uurien** [comment]
I see some references in the code that are not modified in the PR, shouldn't they be removed also?
- https://github.com/DataDog/dd-trace-js/blob/master/integration-tests/ci-visibility/run-jest.mjs
- https://github.com/DataDog/dd-trace-js/blob/master/integration-tests/ci-visibility/run-jest.js
- Comment here: https://github.com/DataDog/dd-trace-js/blob/962bccc91f04119e56e7ad046d99e69882a03522/packages/datadog-plugin-jest/src/index.js#L70

**Comment by juan-fernandez** [comment]
> I see some references in the code that are not modified in the PR, shouldn't they be removed also?
> 
> * https://github.com/DataDog/dd-trace-js/blob/59cb67b534c7bdda13855aba633713a272014266/integration-tests/ci-visibility/run-jest.mjs#L22
> * https://github.com/DataDog/dd-trace-js/blob/59cb67b534c7bdda13855aba633713a272014266/integration-tests/ci-visibility/run-jest.js#L20
> * Comment here: https://github.com/DataDog/dd-trace-js/blob/962bccc91f04119e56e7ad046d99e69882a03522/packages/datadog-plugin-jest/src/index.js#L70

yeah I looked at those. I want to keep the first two because they're used for a test to just check whether we crash with `jest-jasmine2` or not, which is a good test to have. About the third I was on the fence, but yeah, I'll remove it

**Comment by juan-fernandez** [comment]
> > I see some references in the code that are not modified in the PR, shouldn't they be removed also?
> > 
> > * https://github.com/DataDog/dd-trace-js/blob/59cb67b534c7bdda13855aba633713a272014266/integration-tests/ci-visibility/run-jest.mjs#L22
> > * https://github.com/DataDog/dd-trace-js/blob/59cb67b534c7bdda13855aba633713a272014266/integration-tests/ci-visibility/run-jest.js#L20
> > * Comment here: https://github.com/DataDog/dd-trace-js/blob/962bccc91f04119e56e7ad046d99e69882a03522/packages/datadog-plugin-jest/src/index.js#L70
> 
> yeah I looked at those. I want to keep the first two because they're used for a test to just check whether we crash with `jest-jasmine2` or not, which is a good test to have. About the third I was on the fence, but yeah, I'll remove it

actually I need to keep all of them: while ci visibility will not work with `jest-jasmine2`, some of the hooks (`jest-environment-node` and others) are still executed, and `JestPlugin` is instantiated. If I don't do that check, dd-trace will make the test run crash. `does not crash when jest uses jest-jasmine2` test fails if I remove this code, so a good thing that we have the test 😄 .

**Comment by uurien** [comment]
ok, if they have been checked an it is a intencional decision 👌

**Review by uurien — APPROVED** [review]

**Pull request merged**
