### PR TITLE
Use protobufjs to test profiles

### PR DESCRIPTION
**Pull request by nsavoire**
### What does this PR do?

Use protobufjs package and generated files from `pprof.proto` testing profiles (decoding of protobuf encoded profiles).

### Motivation
@datadog/pprof/proto/profile is an implementation detail of @datadog/pprof and will soon disappear.

### CODE REVIEW

**Review by Qard — COMMENTED** [review]
What do you think of doing protobuf compatibility testing in pprof-nodejs itself and instead just using pprof-format here? I'd rather avoid leaking protobuf stuff out into dd-trace-js if it can be avoided. 🤔

**Comment by nsavoire** [comment]
> What do you think of doing protobuf compatibility testing in pprof-nodejs itself and instead just using pprof-format here? I'd rather avoid leaking protobuf stuff out into dd-trace-js if it can be avoided. 🤔

I think it's nice having a test here that checks that the exporter generates files that can be decoded by a reference implementation.

**Comment by r1viollet** [comment]
@Qard I think this mechanism is nice (as we don't expose the dependency to users). It adds an integration check that does not depend on our own implementation of pprof.

**Comment by r1viollet** [comment]
This PR is blocking our profiling release.

**Review by Qard — APPROVED** [review]

**Comment by nsavoire** [comment]
Closing pull-request, having a dependency on protobufjs is not desirable. Switched to using pprof-format to decode profiles.

**Pull request closed without merging**
