### PR TITLE
Protect req.socket.remoteAddress in appsec reporter

### PR DESCRIPTION
**Pull request by uurien**
### What does this PR do?

Protect `req.socket.remoteAddress` for the use cases when `req.socket` is empty.

### Motivation

Detected logs with the failure.

### CODE REVIEW

**Review by CarlesDD — DISMISSED** [review]

**Comment by CarlesDD** [comment]
Worth adding a test?

**Review by IlyasShabi — DISMISSED** [review]
[NIT] Is it possible to have a test for this ?

**Comment by uurien** [comment]
@simon-id 
> how does a req not have a socket??

I saw this happening in the logs, and the doc says that this could be null: https://nodejs.org/docs/latest/api/http.html#messagesocket

> unless the user specified a socket type other than [<net.Socket>](https://nodejs.org/docs/latest/api/net.html#class-netsocket) or internally nulled

**Review by simon-id — APPROVED** [review]
a bit weird cuz i can't find a place where the socket would get removed in node core, but i don't have time to investigate this more

**Review by CarlesDD — APPROVED** [review]

**Pull request merged**
