### PR TITLE
[ci-visibility] Split cypress integration tests

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
* Split cypress integration tests into its own job.
* Do browser dependency installation in the workflow file rather than programatically in the test. 

### Motivation
Cypress dependency installation is slow. Doing it at the test increases the risk of timing out.

### CODE REVIEW

**Review by rochdev — CHANGES_REQUESTED** [review]
As discussed offline, this would keep the flakiness in v2.x branch. Let's make sure it's also fixed there.

**Comment by juan-fernandez** [comment]
I'll wait for https://github.com/DataDog/dd-trace-js/pull/2955 to be merged to continue on this

**Comment by juan-fernandez** [comment]
let's wait for https://github.com/DataDog/dd-trace-js/pull/2957 to see the real benefit of this

**Comment by juan-fernandez** [comment]
I'm not convinced by this anymore: testing locally (which I often do) becomes way more difficult and given how CI integration tests are structured right now we wouldn't be saving much time either. I'll close this PR and open a new one to increase the timeout of the cypress installation, which was causing trouble

**Pull request closed without merging**
