### PR TITLE
fix(openai): tracing occurs in correct async context

### PR DESCRIPTION
**Pull request by sabrenner**
### What does this PR do?
Ensures tracing and parentage is tracked appropriately across different async contexts by migrating the OpenAI plugin to use tracing channel/appropriate internal APIs.

### Motivation
Previously, something like:
```javascript
await tracer.trace('outer', async () => {
  await openai.chat.completions.create(...)
  tracer.trace('child', () => {})
})
```
Would have `child` as a child span of the `openai.request` span, and not the `outer` span. By migrating to tracing channel and using the internal APIs for later versions, this parentage/context is maintained. This is validated with a regression test, for both streamed and non-streamed cases.

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Comment by rochdev** [comment]
> By properly wrapping the traced functions in a shared async resource, this parentage/context is maintained.

Using `AsyncResource` alters the async context for all code in the process. Could we instead switch the `openai` integration over to `TracingChannel` to avoid unintended side-effects of altering the async stack?

**Comment by sabrenner** [comment]
> Could we instead switch the openai integration over to TracingChannel to avoid unintended side-effects of altering the async stack?

For sure! I think this should be pretty doable for the patching of older versions of OpenAI (`<=3`), but I'm wondering if it would be a bit harder for the newer patching because of how we currently trace streamed responses (based on my understanding of TracingChannel). Happy to chat offline with more details, but if we have an instance of a more complex migration of an integration to TracingChannel, that might help me out.

**Comment by rochdev** [comment]
> if we have an instance of a more complex migration of an integration to TracingChannel, that might help me out.

There are `grpc` and `http` that both use the lower-level API since they are also stream-based.

**Comment by sabrenner** [comment]
@rochdev thanks! I think I've implemented this correctly, the test I added is still passing for both streamed and non-streamed cases, and i think it's following established patterns for other `TracingChannel` migrations for other plugins.

**Review by Qard — APPROVED** [review]

**Pull request merged**
