### PR TITLE
Update axios to 0.21.1 to address CVE

### PR DESCRIPTION
**Pull request by mlarraz**
### What does this PR do?
Minor version bump on dependency

### Motivation
See https://github.com/advisories/GHSA-4w2v-q235-vp99

### CODE REVIEW

**Review by rochdev — APPROVED** [review]

**Comment by Itsindigo** [comment]
@rochdev @mlarraz -- I think the deploy failed on this, could you release again please?

**Comment by adamwitko** [comment]
I think the deploy failed on this, could you re-run the pipeline again please?

**Comment by noelleleigh** [comment]
When will a new release be published that includes this fix?

**Comment by bengl** [comment]
This is now released in `v0.29.2`.

**Pull request merged**
