### PR TITLE
Fix benchmark issues

### PR DESCRIPTION
**Pull request by jbertran**
### What does this PR do?

Service naming (#2941) _is_ the culprit for the recent benchmark issues, this PR tries to identify the cause and fix it.

### CODE REVIEW

**Comment by tlhunter** [comment]
Maybe try commenting out just the changes in plugin manager, test that, comment out just hte changes in config, test that, etc.

Tests will of course fail but see if the benchmark results improve.

**Comment by tlhunter** [comment]
Hopefully https://github.com/DataDog/dd-trace-js/pull/3150 fixes the log benchmark issues. I haven't yet tried to fix the startup issues.

**Comment by tlhunter** [comment]
I'm rebasing on master now that some benchmark changes landed. Hopefully the log benchmark issues disappear.

**Comment by tlhunter** [comment]
Apparently #3150 had no affect?! The results are exactly the same.

**Comment by jbertran** [comment]
Comparing with the previous benchmark, we've removed `cpu_user_time` ballooning for _most_ of the log benchmarks. #3146, which I've also rebased, exhibits the same behaviour.

The interesting part for the log benchmark is that the `without-log` scenario is showing the same performance hit as the rest, so it's possible that none of the scenarios actually log messages for some reason.

**Pull request closed without merging**
