### PR TITLE
Clean up JUnit reporting code 

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
Remove code related to junit files upload.

### Motivation
Now that we're migrating to `tap`, the `datadog-ci junit upload` code no longer does anything.

### CODE REVIEW

**Comment by rochdev** [comment]
Any way to make this work with tap instead? There seems to be tools to convert from tap output to JUnit, maybe we could use that?

Sidenote: It would be useful to have TAP format support directly in the product.

**Comment by juan-fernandez** [comment]
> Any way to make this work with tap instead? There seems to be tools to convert from tap output to JUnit, maybe we could use that?
> 
> Sidenote: It would be useful to have TAP format support directly in the product.

yeah it's possible. I see a junit reporter https://github.com/dhershman1/tap-junit#readme. This might take a bit so maybe we do it in another PR? Or you want to keep this code in place?

**Comment by rochdev** [comment]
> This might take a bit so maybe we do it in another PR? Or you want to keep this code in place?

Actually, let me see if I can maybe retrofit this quickly, assuming the output is the same.

**Review by rochdev — APPROVED** [review]
There is only 1 library converting tap to JUnit and it doesn't work. I would say we need to either support tap directly, or XUnit which tap can also output, to make this work. I'll leave it to you to decide if you want to keep the code or discard it and redo this later.

**Comment by rochdev** [comment]
It's worth noting that Node built-in runner only supports tap as output, so that would definitely be the better choice if we want to move to that later on.

**Pull request merged**
