### PR TITLE
always enable tracing header injection for AWS requests

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- always injects aws tracing headers
- see #3796, #205, #3719 for more information

### Motivation
- I don't believe this has caused issues for users in years
- users are complaining that this isn't the default behavior
- users are unable to programmatically change config in certain environments
  - technically this could be solved by adding another env var

### Plugin Checklist

- [x] Unit tests.
- [x] TypeScript [definitions][1].
- [x] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Review by Qard — APPROVED** [review]

**Review by wconti27 — APPROVED** [review]

**Comment by Romack** [comment]
Just want to point out that removing `enablePropagationWithAmazonHeaders` from the types file is a breaking change and should've been a major version update.  Any typescript projects that that have implemented this "workaround" (e.g. us) will receive the following error if/when they upgrade dd-trace to version 5.23.1

Object literal may only specify known properties, and 'enablePropagationWithAmazonHeaders' does not exist in type 'http'.

**Comment by alxgrk** [comment]
Unfortunately, this change broke our production environment, because it made AWS requests fail. Specifically, it it the following request that fails:
```js
const {S3} = require('@aws-sdk/client-s3');
const awsS3Client = new S3();
const response = await awsS3Client
      .getObject({
        Bucket: 'my-bucket',
        Key: 'my-file',
        IfNoneMatch: 'my-etag',
      });
```
We tested both, with `aws-sdk@2.884.0` as well as with `@aws-sdk/client-s3@3.673.0` - same result.

From reading the different PRs/issues, it looks like since 2018 ([here](https://github.com/DataDog/dd-trace-js/pull/205)) the exception for signed AWS requests existed. In November 2023, it got removed ([here](https://github.com/DataDog/dd-trace-js/pull/3796)), but reverted on the same day ([here](https://github.com/DataDog/dd-trace-js/pull/3799)), because some users were facing issues. For some reason that I can not yet understand, it was assumed in [this PR](https://github.com/DataDog/dd-trace-js/pull/4717) that the errors won't show up again. Is there any reason that led to this assumption?
As a workaround, we reverted to 5.22.0, but of course this error prevents us from upgrading.

PS: I have also submitted a helpdesk request, but wanted to make this problem visible to others as well.

**Comment by tlhunter** [comment]
@alxgrk from the research I had done it appeared that Amazon had fixed the bug which caused any arbitrary header to affect the signature. I didn't realize this was only fixed with SDK v3 and not with v2.

We'll work on reverting this change, perhaps just for SDK v2 and not for v3.

**Comment by alxgrk** [comment]
thanks @tlhunter , sounds like a plan 👍

**Comment by tmercswims** [comment]
This change broke our production as well. We still use aws-sdk v2, and get a signature mismatch error on requests to DynamoDB. Downgrading to 5.22.0 fixes the errors.

**Pull request merged**
