### PR TITLE
Update trace propagation format for aws-sdk direct invocations

### PR DESCRIPTION
**Pull request by agocs**
### What does this PR do?

Updates the trace propagation format for aws-sdk direct lambda invocations. The old way was:

```
clientContext: {
  custom:{
    _datadog: {
      x-datadog-trace-id: "",
      x-datadog-parent-id: "",
      ...
    }
  }
}
```

New way is:

```
clientContext: {
  custom: {
      x-datadog-trace-id: "",
      x-datadog-parent-id: "",
      ...
  }
}
```

I've added a configuration option called `invokeWithLegacyContext` (default `false`) that causes aws-sdk.invoke operations to use the legacy trace propagagtion format. I'm not sure where to document the versions of datadog-lambda-py and datadog-lambda-js that are compatible with the new format.

### Reasoning

The Go and Java runtimes only support `ClientContext.custom` fields of type `map[string]string`. C.f. :
- https://github.com/aws/aws-lambda-java-libs/issues/212
- https://github.com/DataDog/dd-trace-js/issues/1312

In order to pass trace contexts to directly invoked Go and Java lambda functions, we can write the trace context key:values to ClientContext.custom rather than creating a ClientContext.custom._datadog object like we've been doing.

### Backwards compatibility

This is, strictly speaking, a breaking change in how we add trace context to direct invocations. The Python and JS repos have already been updated to accept the new format:
- https://github.com/DataDog/datadog-lambda-js/pull/194
- https://github.com/DataDog/datadog-lambda-python/pull/146

They both check for the old and new formats. 

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Review by bengl — COMMENTED** [review]
LGTM, but I think it might be semver-major. Maybe we can default to the "legacy" way now, and save changing the default for an upcoming major rev?

@rochdev what do you think?

**Comment by agocs** [comment]
Hey @bengl , I flipped `invokeWithLegacyContext` such that it defaults true. Once this is merged, should I queue up another PR to flip it back, tagged with the `2.0.0` milestone?

**Comment by agocs** [comment]
Per our conversation on Slack, I've pulled out the `invokeWithLegacyContext` option because the old way can crash Java and Go lambda functions, but the worst that's going to happen the new way is that an older version of datadog-lambda-python or datadog-lambda-js won't be able to find the trace context.

**Review by rochdev — APPROVED** [review]

**Comment by agocs** [comment]
Hm, it looks like Codecov doesn't like that I decreased the overall line count. Is this a blocker?

**Comment by rochdev** [comment]
> Hm, it looks like Codecov doesn't like that I decreased the overall line count. Is this a blocker?

Not a blocker.

**Pull request merged**
