### PR TITLE
fix rhea memory leak concerning inFlightDeliveries

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- moving #3823 to allow CI to run
- all the background for these changes are in that original PR

### Motivation
- fixes #3823

### CODE REVIEW

**Comment by rochdev** [comment]
Not sure I understand this change. It adds a property that is never used anywhere. How can that be fixing any issue?

**Comment by tlhunter** [comment]
@rochdev I applied the following code both to master and to the branch for this PR:

```diff
diff --git a/packages/datadog-instrumentations/src/rhea.js b/packages/datadog-instrumentations/src/rhea.js
index 955b72b67..11e9f3375 100644
--- a/packages/datadog-instrumentations/src/rhea.js
+++ b/packages/datadog-instrumentations/src/rhea.js
@@ -218,6 +218,7 @@ function addToInFlightDeliveries (connection, delivery) {
 
 function beforeFinish (delivery, state) {
   const obj = contexts.get(delivery)
+  console.log('>>> beforeFinish: context has .connection?', 'connection' in obj)
   if (obj) {
     if (state) {
       dispatchReceiveCh.publish({ state })
```

Then ran the Rhea tests:

```sh
PLUGINS=rhea yarn test:plugins:ci
```

When they run in master the output is always the same, there is no connection available:

```
>>> beforeFinish: context has .connection? false
>>> beforeFinish: context has .connection? false
```

But, when I run this code in the branch based on this PR, the connection is available:

```
>>> beforeFinish: context has .connection? true
>>> beforeFinish: context has .connection? true
```

Further, a check for `!!obj.connection[inFlightDeliveries]` also returns true.

**Comment by tlhunter** [comment]
Also, I can delete this check now:

```diff
diff --git a/packages/datadog-instrumentations/src/rhea.js b/packages/datadog-instrumentations/src/rhea.js
index f38e7d671..89365d66a 100644
--- a/packages/datadog-instrumentations/src/rhea.js
+++ b/packages/datadog-instrumentations/src/rhea.js
@@ -224,9 +224,7 @@ function beforeFinish (delivery, state) {
     if (state) {
       dispatchReceiveCh.publish({ state })
     }
-    if (obj.connection && obj.connection[inFlightDeliveries]) {
-      obj.connection[inFlightDeliveries].delete(delivery)
-    }
+    obj.connection[inFlightDeliveries].delete(delivery)
   }
 }
 ```

When deleted in master, the tests fail, but when deleted in this PR, they pass.

**Review by rochdev — CHANGES_REQUESTED** [review]
Looks like this is missing a test then if everything was passing even though that code never worked. Also, the code should stay defensive as before, because otherwise if the library stops assigning `this.connection` it will result in an error. Although a memory leak is not much better so the defensive code should probably be improved.

**Comment by tlhunter** [comment]
@rochdev a test has been added

**Review by rochdev — APPROVED** [review]

**Comment by rochdev** [comment]
That test is really tied to the implementation, but I guess it's better than nothing, at least it validates that the code has been run as it should.

**Pull request merged**
