### PR TITLE
fixes types mismatch in `User` interface

### LINKED ISSUE #3707: Type Mismatch in `setUser` Method for Datadog Tracer
**Expected behaviour**

The setUser method in the Datadog Tracer library should accept user attributes of various types including number, boolean, and Date, as evident from actual usage and logs.

image

While this exact payload it's completely valid if bypassed by `@ts-ignore`, type casting or any other method.

image

**Actual behaviour**

The TypeScript definition for the [ `User` interface restricts attributes to be of type string](https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts#L644). This is inconsistent with actual behavior and leads to unnecessary type errors during development.

**Steps to reproduce**

Try using the setUser method with user attributes that are not of type string.

```ts
tracer.setUser({
  id: 1, // number
  email: "test@email.com", // string
  createdAt: new Date(), // Date object
  isEnabled: true, // boolean
});
// TypeScript will throw a type error.
```

### PR DESCRIPTION
**Pull request by paw-j**
### What does this PR do?

This PR updates the User interface in the TypeScript definitions to allow custom fields with types other than string. This change enhances the flexibility of the tracer's methods that reference the User object to handle different types like number, boolean, or Date. Fixes #3707

### Motivation

The current implementation restricts custom fields to string types, which doesn't align with real-world scenarios where we might need to attach more complex or different types of data to a user. An issue has been reported about this limitation, and this PR aims to resolve it.

### Plugin Checklist

- [x] Unit tests.
- [x] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Comment by simon-id** [comment]
This string limitation is actually not an oversight, but a design choice. The dd-trace library is not the only relevant actor here so we can't make that change without mirroring these changes in other places. I will check if we can accept that change.

**Comment by simon-id** [comment]
Even if this would be an acceptable change, this PR is incomplete. There are points in the code that will enforce this string limitation, not just the typescript definition. Example here: https://github.com/DataDog/dd-trace-js/blob/c452005127a99285dfd95affeec64a4d1c1769c4/packages/dd-trace/src/appsec/sdk/set_user.js#L8

**Comment by Qard** [comment]
It needs to be a string or undefined to be used in span tags.

**Comment by Paw-liblab** [comment]
> It needs to be a string or undefined to be used in span tags.

 @Qard  Isn't this a contradictory? 
 
 As I understand @simon-id, this line of code effectively allows other types by converting them to strings.

> Even if this would be an acceptable change, this PR is incomplete. There are points in the code that will enforce this string limitation, not just the typescript definition. Example here:
 ```js
rootSpan.setTag(`usr.${k}`, '' + user[k]) 
```
 
> This string limitation is actually not an oversight, but a design choice. The dd-trace library is not the only relevant actor here so we can't make that change without mirroring these changes in other places. I will check if we can accept that change.

Calling something a "design choice" doesn't automatically make it a good one. If the library is capable of handling different types in practice, then the "design choice" is arguably flawed and should be reconsidered. This seems like an appeal to complexity. 
Sure, there might be other components in the system that rely on this, but if the system as a whole is designed to accommodate various types (as evidenced by the internal string casting), then saying "we can't change just one part" is a cop-out.

**Comment by Qard** [comment]
It _doesn't_ support other types. That's _why_ we're coercing it to a string there.

With TypeScript we have the type safety to ensure it's a string at compile time, but with JS we can only discover that at runtime and we have a policy to never crash user apps.

By coercing to a string we avoid crashing the app, but likely also produce a not-useful value. For example passing in an object will result in the value being `[object Object]`. We should not be allowing that if it can be avoided. Rather than expanding the accepted types it would be better if we could log a warning in cases like those where it's _not_ a string or undefined.

**Comment by Paw-liblab** [comment]
> It _doesn't_ support other types. That's _why_ we're coercing it to a string there.
> 
> With TypeScript we have the type safety to ensure it's a string at compile time, but with JS we can only discover that at runtime and we have a policy to never crash user apps.
> 
> By coercing to a string we avoid crashing the app, but likely also produce a not-useful value. For example passing in an object will result in the value being `[object Object]`. We should not be allowing that if it can be avoided. Rather than expanding the accepted types it would be better if we could log a warning in cases like those where it's _not_ a string or undefined.

Sorry for the late response had a lot of work going on, I agree with the warning approach. One of the main problems I faced was the type not being capable of augmenting `[key: string]: string | undefined`. So this was a big blocker and ended up working more on TS specifics rather than the implementation.

> For example passing in an object will result in the value being `[object Object]`.

@Qard 
I see in the RUM `setUser` being handled by flattening the object, so nested objects show like:
image

Perhaps it might be better to have a unified approach unless there are service specific constraints. When used in plain JS we don't have such warnings.

**Comment by simon-id** [comment]
I'd be willing to accept this PR if you found a way to support accepting ANY value, and properly serializing it to strings, on every use case possible.

**Comment by simon-id** [comment]
I'm closing this issue and the PR with it as there hasn't been any activity or other customer request about this topic.

**Pull request closed without merging**
