### PR TITLE
upgrade to latest @azure/functions version

### PR DESCRIPTION
**Pull request by khanayan123**
### What does this PR do?
upgrades to @azure/functions version 4.6.0

### Motivation
npm audit failing in versions < 4.6.0 since those version have cookie 0.6.0 as a dependency

### CODE REVIEW

**Review by wconti27 — DISMISSED** [review]

**Review by duncanpharvey — CHANGES_REQUESTED** [review]
> registry.npmjs.org

Can you use `yarn` to install the dependencies instead of `npm install`? It should result in fewer changes to the lockfile

**Comment by khanayan123** [comment]
> > registry.npmjs.org
> 
> Can you use `yarn` to install the dependencies instead of `npm install`? It should result in fewer changes to the lockfile

Done!

**Review by wconti27 — DISMISSED** [review]

**Review by duncanpharvey — CHANGES_REQUESTED** [review]
> > > registry.npmjs.org
> > 
> > 
> > Can you use `yarn` to install the dependencies instead of `npm install`? It should result in fewer changes to the lockfile
> 
> Done!

The registry in use is still `registry.npmjs.org`. Can you revert to the original lockfile then rerun `yarn`? Only `@azure/functions` and `cookie` should be changing.

**Review by duncanpharvey — APPROVED** [review]
LGTM!

**Pull request merged**
