### PR TITLE
move @types/node to devDependencies

### PR DESCRIPTION
**Pull request by acommodari**
### What does this PR do?

Move the `@types/node` package from dependencies to devDependencies.

### Motivation

Reduce `dd-trace-js` package size by removing unnecessary prod dependency.

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Comment by acommodari** [comment]
Hmmm maybe I jumped the gun with this PR... Honestly whether to include `@types` in dependencies or devDependencies as a _library_ is not a straightforward decision... I myself don't have much experience with creating Typescript compatible libraries only consuming them.

From what I understand since you are using types from `@types/node` in your own type declarations those typings would be missing if the package was moved to devDependencies and the consumers of this library did not have `@types/node` installed locally? Please correct me if I'm wrong.

In the case of `@types/node` specifically though I think it is a special case. Can we assume that anyone writing Typescript with the node runtime will by default always include `@types/node` as a prod or dev dependency?

The only edge cases I can think of would be if they do have the package installed locally but they have a version < v12. That and if they were writing a plain Javascript project but were taking advantage of their IDE like VSCode for example to give them better typing information as a kind of bonus.

I don't think there is a right or wrong answer here. There is no perfect solution dependencies, devDependencies, or even peerDependencies.

In my case, I am using `dd-trace-js` in a private repo for work and we build our project and exclude devDependencies before deploying it to aws lambda.
Since what we are deploying is js we don't need any types but I noticed `dd-trace-js` had typings that wound up in our deployed `node_modules` folder. Which prompted me to make this PR without really thinking it through as I thought it was an oversight.

I guess lambdas are a special case though because they have hard size limits making users more conscious of the size of their dependencies.

**Comment by rochdev** [comment]
It's definitely a fair point that when not using TypeScript, the additional dependency is just useless overhead. We're currently looking into optimizing dd-trace for serverless, and we could definitely remove the dependency completely but we'd first need to add an integration test to ensure that your theory is correct and the types from the main project would also work for libraries.

**Review by rochdev — APPROVED** [review]
I took a quick look at some of our other projects and it looks like `@types/node` is always added in `devDependencies`.

**Comment by rochdev** [comment]
It looks like this broke one of the benchmarks. Once that's fixed then we can merge this PR 👍 .

**Comment by tlhunter** [comment]
It looks like this PR got a bit stuck for the past year. Is this something you'd still be interested in landing?

**Comment by Qard** [comment]
This appears to have already been done so closing this.

**Pull request closed without merging**
