### PR TITLE
add init script that can be required from cli

### LINKED ISSUE #1017: Provide dd-trace/init script
At the moment, every project I work with has to have a dummy script:

```js
// /init/dd.js
import tracer from "dd-trace";
tracer.init();

```

Then we include that script whenever launching a program, e.g.

```bash
node -r ./dist/init/dd.js ./dist/bin/server.js

```

This is done in such a way because dd must be initialised before importing any modules.

It would be nice if there was an init script that I could use directly from `dd-trace`, i.e.,

```bash
node -r 'dd-trace/init' ./dist/bin/server.js

```

This would save me from creating a redundant file.

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Add script to initialize from CLI.

### Motivation

In some cases, programmatic configuration is not available, or it may simply be easier to add a cross-cutting concern library from CLI instead.

Closes #1017

### CODE REVIEW

**Comment by Conduitry** [comment]
It sounds like that new direction for this PR wouldn't help in my case then. Shall I open a new issue about the problems with using `dd-trace` in an app bundled by Rollup?

**Comment by rochdev** [comment]
> It sounds like that new direction for this PR wouldn't help in my case then. Shall I open a new issue about the problems with using dd-trace in an app bundled by Rollup?

I may have misunderstood your use case then. Why would the new approach not work? Basically it's the same as with the `init` but we're just trying to avoid having to explicitly write the additional `/init` suffix.

**Comment by Conduitry** [comment]
As far as I can tell, it is difficult or perhaps impossible to get Rollup to place any code before the `require()`s at the top of the bundle for external dependencies.

The instructions in the [quickstart](https://docs.datadoghq.com/tracing/setup/nodejs/#quickstart) do not appear to be bundler-friendly (or at least not Rollup-friendly), because, even if the tracer is imported and inited in a separate file, only the `require('dd-trace')` ends up before the rest of the `require()`s at the top, and the `tracer.init()` ends up after them, and so when it hooks into `require`, it's already too late to automatically instrument the various built-in Node modules.

Having a `dd-trace/init` as an external module would help with this, because I could just start the main entrypoint of my app with `import 'dd-trace/init'` which would result in the first line of the bundled app being `require('dd-trace/init')` and allowing the automatic instrumentation to work correctly. If the plan is to bake this behavior into `require('dd-trace')`, I don't know how it would be able to tell - when used from a bundled CommonJS app - whether it should implicitly call `init()`.

What is the root `dd-trace` module going to be looking at to determine whether to call `init()`? Having this be explicit (with a separate entry point) sounds to me like a better API design anyway, since it avoids this potential confusion of what loading that module will do.

**Comment by rochdev** [comment]
@Conduitry For your case it should be possible to use the TypeScript snippet from the quickstart page you linked. Even though it says TypeScript it applies to JavaScript as well if a bundler is involved. Basically you would build your own equivalent of `init`.

```js
// server.js
import './init'; // must come before importing any instrumented module.

// init.js
import tracer from 'dd-trace';
tracer.init(); // initialized in a different file to avoid hoisting.
export default tracer;
```

I didn't think about the use case of adding a one-liner import in the code as opposed to as a CLI option, so that's a good point. I guess we could merge this PR and also add an additional PR to detect the command-line to make it easier, they are not mutually exclusive.

@bengl Thoughts on adding `dd-trace/init` for use in code?

**Comment by Conduitry** [comment]
That's what I already did, and that's what resulted in `var tracer = require('dd-trace');` being at the top of the block of `require()`s but the `tracer.init();` being after them. Rollup is pulling all of the `require()`s to the top of the file, presumably because it doesn't expect any other code to hook into or to change what `require()` means.

I'd be happy with either a way to work around this (like `dd-trace/init`) or with a note somewhere on how to make Rollup not do this. I poked around for a while today trying to find a nice way to make Rollup do what I want and ended up with something that works but which is definitely a hack and which I'm definitely not thrilled about.

**Comment by Conduitry** [comment]
See [this example](https://rollupjs.org/repl/?version=2.26.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGdHJhY2VyLmpzJyUzQiU1Q24lNUNuaW1wb3J0JTIwZnMlMjBmcm9tJTIwJ2ZzJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnRyYWNlci5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjB0cmFjZXIlMjBmcm9tJTIwJ2RkLXRyYWNlJyUzQiU1Q24lNUNudHJhY2VyLmluaXQoKSUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHRyYWNlciUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) in Rollup's REPL for the code that is generated. The `.init()` call happens after the other `require()`s.

**Comment by devsnek** [comment]
es imports are always hoisted to the top, even without transpiling. you'd need to use node's `--require` cli argument to preempt that.

**Comment by rochdev** [comment]
@Conduitry It's definitely a common enough use case since it affects every bundlers to various degree. It's something that will be fixed eventually, but in the meantime the only option will be the workaround.

**Comment by rochdev** [comment]
@Conduitry Ended up adding the PR in its current form to 0.25.0. Please let me know if that solves your use case since you can now do both `require('dd-trace/init')` and `node -r dd-trace/init main.js`.

**Comment by Conduitry** [comment]
I see the file in the repo, but the published package does not appear to contain the file. https://unpkg.com/dd-trace@0.25.0/init.js

**Comment by Conduitry** [comment]
I can confirm that running `npm pack` in this repo does not include `init.js` in the archive it builds. `package.json` probably needs updating to include this file in the package.

**Comment by rochdev** [comment]
Correct, sorry about that, will be fixed in 0.25.1 when #1065 lands.

**Comment by rochdev** [comment]
@Conduitry Should be fixed now in 0.25.1.

**Comment by Conduitry** [comment]
Yep, this is working for me now in 0.25.1, thank you!

**Pull request merged**
