### PR TITLE
Add support for subscriptions in the GraphQL plugin

### LINKED ISSUE #248: Doesn't support subscriptions
[This PR](https://github.com/DataDog/dd-trace-js/pull/180/files) added support for mutations but there's still no support for subscriptions. We need to add `subscription` to the types array.

```tsx
const types = ['query', 'mutation', 'subscription']
```

Without this change every subscription call is crashing my app. With the change made everything works as expected.

### PR DESCRIPTION
**Pull request by clayne11**
Fixes #248.

### CODE REVIEW

**Comment by clayne11** [comment]
It looks like something is wrong with the test set up. Node 4 is failing to due to engine incompatibility.

**Comment by rochdev** [comment]
Node 4 tests are broken at the moment because of one of the supported libraries that dropped support for Node 4. We will have to add a way to disable tests for such libraries. For now feel free to ignore Node 4 tests specifically. I'll make sure that Node 4 is not actually broken before releasing new versions.

One question that I have about subscriptions, is do they really work the same as queries and mutations? For example, queries and mutations use the request/response pattern, so they have an explicit start and end. Are subscriptions handled in the same way? What are the start and end times for a subscription?

**Comment by clayne11** [comment]
They definitely work a bit differently. The initial call for a subscription sets up the subscription, which uses a call / response pattern.

After that, when the triggering event occurs on the server, the query that the client passed in the subscription set up is run and that data is returned to the client. 

It probably can't be measured in exactly the same way as mutations, but adding `subscription` into the types array definitely solved the error I was seeing.

**Comment by rochdev** [comment]
So if I understand correctly, for the initial call, the behavior is the same as queries and mutations, so for that call it would be correct to simply add the type? Then we can add support for subscription events in a later version.

**Comment by clayne11** [comment]
I think that sounds reasonable.

**Pull request merged**
