### PR TITLE
index.d.ts: add child_process

### PR DESCRIPTION
**Pull request by ikonst**
### What does this PR do?

This seems to have been omitted in https://github.com/DataDog/dd-trace-js/pull/3608.

### Motivation
Being able to disable this plugin.

### CODE REVIEW

**Comment by simon-id** [comment]
@ikonst Hello and thank you for the contribution!
Could you please provide a little snippet of code that you were expecting to work ? So we can understand the meaning of the PR better, and to reproduce it and create a test for it.

**Comment by ikonst** [comment]
```
tracer.use("child_process", { enabled: false });
```

**Comment by CarlesDD** [comment]
@ikonst I've recreated your PR in #4306 to allow the CI to run. I've cherrypicked your commit so you keep authorship!

**Comment by CarlesDD** [comment]
Released in [v4.38.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.38.0) / [v5.14.0](https://github.com/DataDog/dd-trace-js/releases/tag/v5.14.0)

**Pull request closed without merging**
