### PR TITLE
restify: resolve 0th promise arg, not arguments

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- resolves the 0th argument of the restify controller promise
- currently resolving the array-like `arguments` object

### Motivation
- fixes a customer issue

### CODE REVIEW

**Review by szegedi — APPROVED** [review]
This looks like it was fun to debug.
🚢

**Review by sabrenner — APPROVED** [review]

**Review by rochdev — COMMENTED** [review]
No test was failing for this?

**Review by Qard — CHANGES_REQUESTED** [review]
Can you add a test verifying this to ensure it doesn't regress in the future?

**Comment by tlhunter** [comment]
Based on @AndrewCsontos's comment about the log I realized that the Restify tests do in fact trigger a warning when run in the master branch:

```
$ ./node_modules/.bin/mocha --colors --exit -r "packages/dd-trace/test/setup/mocha.js" packages/datadog-plugin-restify/test/index.spec.js

  Plugin
    restify
      with restify >=3 (11.1.0)
        without configuration
(node:94830) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
          ✓ should do automatic instrumentation
          ✓ should support routing
{"level":40,"time":1702423657582,"pid":94830,"hostname":"COMP-GGKL43TT97","name":"restify","value":{},"msg":"Discarded returned value from async handler"}
{"level":40,"time":1702423657584,"pid":94830,"hostname":"COMP-GGKL43TT97","name":"restify","value":{},"msg":"Discarded returned value from async handler"}
          ✓ should support routing with async functions and middleware
          ✓ should run handlers in the request scope
          ✓ should support array middleware
          ✓ should keep user stores untouched
          ✓ should allow handleUncaughtException

  7 passing (201ms)
```

However, in my branch, there was no warning log. So I added a test that fails if the log is made while still printing the message to stderr to aid with future debugging.

**Review by Qard — APPROVED** [review]

**Pull request merged**
