### PR TITLE
V3.42.0 proposal

### PR DESCRIPTION
**Pull request by khanayan123**
### Bug Fixes

- **profiling**: add source code integration tags to profiles (#3821)
- **core**: do not report HTTP requests over 5 seconds as errors on Node 20 (#3853)
- **core**: update protobuf for security reasons (#3851)
- **core**: resolve the 0th argument of the restify controller promise (#3818)

### Improvements

- **core**: collapse Next.js static resources to reduce cardinality (#3809)
- **civisibility**: waits for git to upload and re-request settings when `require_git` field is `true` (#3790)
- **civisibiity**: do not report total code. coverage if itr is enabled (#3828)
- **profiling**: Add DNS events to timeline (#3822)
- **core**: add a new `http` service configuration option `enablePropagationWithAmazonHeaders` (#3836)
- **appsec**: use existing response header instrumentation to detect Header Injection vulnerability when a unsafe string is written in a header (#3813)
- **profiling**: Add Net events to timeline (#3832)
- **core**: Partially upgrade instrumentation telemetry from v1 to v2 (#3827)
- **civisibility**: Speed up git unshallow (#3839)
- **core**: add a new environment variable to enable span leak detection at either logging or logging + manual gc modes (#3849)
- **core**: add a GitHub security policy via SECURITY.md (#3863)
- **appsec**: Apply new rules for header injection detection to prevent false positives (#3867)
- **dsm**: Add Kafka offset lag to metrics sent by datastreams monitoring (#3761)
- **profiling**: reduce overhead by removing lane logic from profiler library (#3880)

### Features

- **appsec**: add support for schema extraction when calling the waf (#3685)
- **core**: add automatic instrumentation support for Aerospike v3.16.2 - v3.16.7, v4, v5 (#3830, #3804)

### CODE REVIEW

**Review by rochdev — DISMISSED** [review]

**Comment by tlhunter** [comment]
```
  1) packages/dd-trace/test/telemetry/index.spec.js telemetry should send app-started expected { appsec: { enabled: true }, …(1) } to deeply equal { appsec: { enabled: true }, …(1) }:
     Error: expected { appsec: { enabled: true }, …(1) } to deeply equal { appsec: { enabled: true }, …(1) }
      at packages/dd-trace/test/telemetry/index.spec.js:90:62
      at testSeq (packages/dd-trace/test/telemetry/index.spec.js:761:3)
```

seeing a few instances of this error

**Comment by tlhunter** [comment]
Looks like sharedb recently broke comatibility with old versions of Node.js:
https://github.com/share/sharedb/commit/06cc3877fd9b53d1ddc3ecdd3df11f68fbdbb100#diff-3fb720f70ea34fb2975fd6c38ac4b6b6131373be2abfa4760dfaae8a25daaee2

Not that this particular problem should block this release

**Comment by khanayan123** [comment]
> ```
>   1) packages/dd-trace/test/telemetry/index.spec.js telemetry should send app-started expected { appsec: { enabled: true }, …(1) } to deeply equal { appsec: { enabled: true }, …(1) }:
>      Error: expected { appsec: { enabled: true }, …(1) } to deeply equal { appsec: { enabled: true }, …(1) }
>       at packages/dd-trace/test/telemetry/index.spec.js:90:62
>       at testSeq (packages/dd-trace/test/telemetry/index.spec.js:761:3)
> ```
> 
> seeing a few instances of this error

Reached out to @ida613 should be a quick fix and then I can add it to the release

**Comment by khanayan123** [comment]
> Looks like sharedb recently broke comatibility with old versions of Node.js: [share/sharedb@06cc387#diff-3fb720f70ea34fb2975fd6c38ac4b6b6131373be2abfa4760dfaae8a25daaee2](https://github.com/share/sharedb/commit/06cc3877fd9b53d1ddc3ecdd3df11f68fbdbb100#diff-3fb720f70ea34fb2975fd6c38ac4b6b6131373be2abfa4760dfaae8a25daaee2)
> 
> Not that this particular problem should block this release.
> 
> Actually, the code in their library looks like this:
> 
> ```js
> exports.hasOwn = hasOwn = Object.hasOwn || Object.prototype.hasOwnProperty.call;
> ```
> 
> The failing test runs with Node.js v14.21.3. However, I see that the above code works fine locally with that version of Node.js so I'm not sure what's up.

Just tested locally with master & node engine set to node >= 14. I see the same test failures

**Comment by tlhunter** [comment]
https://github.com/DataDog/dd-trace-js/pull/3881 here's a PR to stop testing sharedb against node v14

**Review by tlhunter — APPROVED** [review]

**Pull request merged**
