### PR TITLE
[ci-app] Support Cucumber >=7.3.0

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
* Support newer version of cucumber-js.

### Motivation
* Keep up with latest release of cucumber.js.

### CODE REVIEW

**Comment by rochdev** [comment]
Is the new version actually not supported or it's just the tests?

**Comment by juan-fernandez** [comment]
> Is the new version actually not supported or it's just the tests?

actually not supported. They use different file names

**Comment by rochdev** [comment]
Any quick fix we can do here? Removing support for a library is considered a breaking change, so this would effectively be leaving a bug in.

**Comment by juan-fernandez** [comment]
> Any quick fix we can do here? Removing support for a library is considered a breaking change, so this would effectively be leaving a bug in.

oh ok, I'll have a look. I thought this was the standard procedure.

**Comment by juan-fernandez** [comment]
@rochdev ok got it working with the latest version :-)

**Review by rochdev — APPROVED** [review]

**Pull request merged**
