### PR TITLE
Remove `performance-now` and make sure the reference is fetched at the beginning

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
* Remove `performance-now`
* Substitute by `perf_hooks`
* Fetch reference to `perf_hooks` and `Date.now` right away

### Motivation
It can be safely substituted by `require('perf_hooks').performance.now`.

Also, we want to make sure that even if users mock `performance.now` or `Date.now`, the calculated times are correct.

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

**Comment by simon-id** [comment]
Did you benchmark if this was actually faster ?

**Comment by juan-fernandez** [comment]
> Did you benchmark if this was actually faster ?

no but this is a good idea. In any case, all `performance-now` does is to try to get a hold of `performance.now`, then `process.hrtime` then `Date.now`

**Comment by juan-fernandez** [comment]
> > Did you benchmark if this was actually faster ?
> 
> no but this is a good idea. In any case, all `performance-now` does is to try to get a hold of `performance.now`, then `process.hrtime` then `Date.now`

https://github.com/myrne/performance-now/blob/master/src/performance-now.coffee

**Review by uurien — APPROVED** [review]

**Review by simon-id — APPROVED** [review]

**Review by rochdev — DISMISSED** [review]

**Comment by juan-fernandez** [comment]
@rochdev I had to merge master because of a conflict

**Review by uurien — APPROVED** [review]

**Pull request merged**
