### PR TITLE
v2.38.0

### PR DESCRIPTION
**Pull request by tlhunter**
### Features
- core: add instrumentation for the openai package (#3155)
- waf: automated user events (#3205)
- ci-visibility: support CI Visibility's manual API (#3202)
- core: telemetry metrics for OTel (#3259)
### Improvements
- core/service naming: peer service computation (#3177)
- core/service naming: apply service naming workflow to databases  (#3256)
- core/service naming: make http server plugins `ServerPlugins` (#3261)
- core/service naming: moleculer - service naming (#3281)
- core/service naming: move next plugin to ServerPlugin (#3287)
- iast: taint express route parameters (#3187)
- profiling: enable by default export of a last heap profile when Node.js runs out of heap memory (#3292)
- ci-visibility: more verbose logging for git upload (#3251)
### Bug Fixes
- pg: retain prototype when injecting DBM comment (#3307)
- build: fix s3 package upload (#3218)
- pg: update error string comparison in test (#3295)

### CODE REVIEW

**Comment by tlhunter** [comment]
# Failures

## Postgres

This issue isn't obvious. Seems like we're expecting `client.query` to be a promise in the code but the v2 branch is testing an ancient version of the pg library.

```
  1) Plugin
       pg
         with pg >=4.5.5 (4.5.5)
           when using pg.Client
             service and operation naming
               in version v0
                 should conform to the naming schema:
     TypeError: client.query(...).then is not a function
      at /home/runner/work/dd-trace-js/dd-trace-js/packages/datadog-plugin-pg/test/index.spec.js:202:16
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:126:14)
```

## HTTP

Possibly due to the merge conflict from first commit but I'm not sure.

```
  1) Plugin
       http/server
         canceled request
           should send traces to agent:

      AssertionError: expected { type: 'http', …(11) } to have property 'service' of 'test', but got 'test-http-client'
      + expected - actual

      -test-http-client
      +test
```

## Integration (all 5 of them)

Probably due to the merge conflict in the first commit.

```
  2) startup
       programmatic
         works for options.port:
     Error: the array [
  {
    "actual": "web.request"
    "expected": "http.request"
    "message": "expected { type: 'web', …(11) } to have property 'name' of 'http.request', but got 'web.request'"
    "showDiff": true
  }
  "Error: timeout"
] was thrown, throw an Error :)
```

**Comment by tlhunter** [comment]
So the conflict comes down to [this file in this pull request](https://github.com/DataDog/dd-trace-js/pull/3261/files#diff-e960bd7eefcc7a6b096177d9dddb407e679bcd02e768e2b832f77bffd4e31184). In the pull request the following line remains the same:

```js
    const span = web.startSpan(this.tracer, this.config, req, res, 'web.request')
```

However, in the [conflicted change](https://github.com/DataDog/dd-trace-js/pull/3315/commits/6b88f0cbfe64515e0f7f6be7fe0bcce07e6cd71f#diff-07137cfb62cb0e02272e1e915181999af21211ca58fd8f1167a8fe9eaad45b72), the line changes like so:

```diff
-      const span = web.startSpan(this.tracer, this.config, req, res, 'http.request')
+      const span = web.startSpan(this.tracer, this.config, req, res, 'web.request')
```

So it seems that the v2.x branch expects a value of http.request while v3.x and v4.x expects web.request.

**Comment by tlhunter** [comment]
According to Roch, `web.request` is for server (ingress) and `http.request` is for client (egress). It sounds like the v2 releases used incorrect names. I'm now attempting to switch back to the incorrect name for v2 line. However there are probably a ton of new tests that rightly look for `web.request` that will also need to be changed.

**Comment by tlhunter** [comment]
Alright, it looks like that change (a new commit, the second in line) fixed everything except for the pg bug. For that maybe we bump the supported pg version range since the failing version is incredibly old?

**Comment by tlhunter** [comment]
The final failing test, aws-sdk, has started failing everywhere as of an hour or two ago:
https://github.com/DataDog/dd-trace-js/pull/3314

**Review by juan-fernandez — DISMISSED** [review]
OK from ci visibility's perspective

**Review by uurien — DISMISSED** [review]

**Review by bengl — APPROVED** [review]

**Review by uurien — APPROVED** [review]

**Pull request merged**
