### PR TITLE
[CI] Enable Fastify suite.js

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by watson** [comment]
* **#4771** <a href="https://app.graphite.dev/github/pr/DataDog/dd-trace-js/4771?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @watson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rochdev** [comment]
This looks like something we'd want to be enabled 🤔 Does it still error if uncommented?

**Comment by watson** [comment]
@rochdev I assume the way you'd test it is by running this command?

```
PLUGINS="fastify" yarn test:plugins:upstream
```

If that's the case, then it actually does pass with the following output after running it:

```
yarn run v1.22.22
$ node ./packages/dd-trace/test/plugins/suite.js
08:29:29 ❯ npm view fastify dist-tags --json
08:29:30 ❯ git clone https://github.com/fastify/fastify.git --branch v5.0.0-alpha.1 --single-branch /var/folders/bz/8vjzx43955l4p8nr7f08hhsw0000gp/T/dd-trace-js-suites-VU5Vyt
08:29:31 ❯ npm install --legacy-peer-deps
08:30:04 ❯ NODE_OPTIONS='-r /Users/thomas.watson/go/src/github.com/DataDog/node_modules/dd-trace/init' node_modules/.bin/tap -J test/*.test.js test/*/*.test.js --no-coverage --no-check-coverage
08:30:04 ❯ rm -rf /var/folders/bz/8vjzx43955l4p8nr7f08hhsw0000gp/T/dd-trace-js-suites-8R0cOm
08:30:04 ❯ node_modules/.bin/tap -J test/*.test.js test/*/*.test.js --no-coverage --no-check-coverage
✨  Done in 34.83s.
```

I'll update the PR...

**Comment by watson** [comment]
I can see that the `suite.js` file was added by @bengl in the commented out state (https://github.com/DataDog/dd-trace-js/pull/1331). So it has never been enabled. I assume it was just a mistake back then 🤷

**Review by rochdev — APPROVED** [review]

**Pull request merged**
